services:
  postgres:
    image: postgres:latest
    container_name: database
    restart: unless-stopped
    expose:
      - "5432"
    env_file:
      - "example.env"

  api:
    build: .
    container_name: api
    command: gunicorn food_project.wsgi:application --bind 0.0.0.0:8000 --workers 4
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - "example.env"